language: python
python:
  - "3.8"
before_install:
  - export MPLBACKEND=Agg


install:
  - pip install -U pip poetry
  - poetry install

script:
  - poetry run pyflakes shifthelper
  - poetry run python -m pytest

env:
  - SHIFTHELPER_CONFIG=tests/resources/test_config.json
